version: '3.1'
services:
  python:
    restart: always
    container_name: jupyter
    build:
        context: .
        dockerfile: Dockerfile.python3
    ports:
        - 127.0.0.1:8888:8888
        - 127.0.0.1:8889:8889
    volumes:
        - ../:/home/notebooks/
    links:
      - "db:database"

  db:
    restart: always
    container_name: postgres
    build:
        context: .
        dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: " "
    ports:
        - 127.0.0.1:5432:5432
    volumes:
        - ../postgres_db:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    volumes:
        - ../mongo_db:/data/db
        #- ../mongo_db:/data/configdb
    ports:
        - 127.0.0.1:27017:27017
        - 127.0.0.1:28017:28017
