FROM postgres:latest

RUN apt-get update
RUN apt-get install -y --allow-unauthenticated postgresql-common
RUN apt-get install -y --allow-unauthenticated postgresql-contrib postgresql-plpython3-11
RUN apt-get install -y --allow-unauthenticated python3-pip

RUN apt-get install -y --allow-unauthenticated --no-install-recommends python3-minimal python3
RUN apt-get install -y --allow-unauthenticated python3-numpy python3-scipy

RUN pip3 install nltk stop-words py_stringmatching
