version: '3.1'
services:
  python:
    restart: always
    container_name: jupyter
    build:
        context: .
        dockerfile: Dockerfile.python3
    ports:
        - 127.0.0.1:8888:8888
        - 127.0.0.1:8889:8889
    volumes:
        - ../:/home/notebooks/
    links:
      - "db:database"

  db:
    restart: always
    container_name: postgres
    build:
        context: .
        dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
        - 127.0.0.1:5432:5432
    #volumes:
    #   -#volume ../postgres_db/data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    container_name: pgadmin
    build:
        context: .
        dockerfile: Dockerfile.pgadmin
    ports:
        - 127.0.0.1:5050:5050
    volumes:
        - ../postgres_db/tmp:/tmp
    links:
      - "db:database"
    environment:
        SERVER_PORT: 5050

  mongo:
    image: mongo
    restart: always
    volumes:
        - ../mongo_db:/data/db
        #- ../mongo_db:/data/configdb
    ports:
        - 127.0.0.1:27017:27017
        - 127.0.0.1:28017:28017
