version: '3.1'

services:
    python:
        restart: unless-stopped
        container_name: jupyter
        build:
            context: .
            dockerfile: Dockerfile.python3
        ports:
            - 127.0.0.1:8888:8888
        volumes:
            - ../:/home/notebooks/
        networks:
            - internal-network

    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        volumes:
            - ../mongo_db:/data/db
        ports:
            - 127.0.0.1:27017:27017
            - 127.0.0.1:28017:28017
        networks:
            - internal-network

    webserver:
        build:
            context: ./
            dockerfile: Dockerfile.plotly
        environment: 
            - VIRTUAL_HOST=dashsimple1.arthoughts.local
        volumes:
            - ../web_application:/myworkdir
        networks:
            - internal-network
        ports:
            - '80:8050'

networks:
    internal-network:
        driver: bridge

